# This is a basic workflow that is manually triggered

name: Update the mirror (Rocky)

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [ master ]
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  update:
    # The type of runner that the job will run on
    runs-on: xinux-mirror

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Fetch & Apply the updates
      run: |
        git fetch
        git pull
      working-directory: /media/xinux/pub/xinux