# This is a basic workflow that is manually triggered

name: Manual workflow (Rocky)

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [ master ]
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  neofetch:
    # The type of runner that the job will run on
    runs-on: xinux

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Neofetch
      run: neofetch

    - name: List the xinux mirror folder
      run: ls -la /media/xinux/pub/xinux